spring:   
  boot:
    admin:
      client:
        url: http://localhost:1111/ 
      
  datasource:
    url: jdbc:mysql://localhost:3306/major_project
    username: root
    password: 1995
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: update    
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'     

server:
  port: 8081

auth-service :
   messages : 
    userReg : User Created Successfully.
    userError : User creation  Failed.
    login : Loggin success.
    loginError : User Credentials is invalid.  
