spring:   
  boot:
    admin:
      client:
        url: http://localhost:1111/ 
      
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce
    username: root
    password: Aman@2000
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'     

server:
  port: 8082

product-service:
   messages:
    categoryAdded: Category Added Successfully
    categoryAddedErr: Category Failed to Add
    categoryUpdate: Category Updated Successfully
    categoryUpdateFail: Category Updated Failed
    categoryFatch: All Category Fetch Successfully
    categoryFatchErr: Failed To Fetch Category
    categorySelect:  Category Retrieved 
    categorySelectErr: Failed to Retrieve
    categoryDelete: Category Deleted Successfully
    categoryDeleteErr: Failed To Deleted
    
    productAdded: Product Added Successfully
    productAddedErr: Product Failed to Add
    productUpdate: Product Updated Successfully
    productUpdateErr: Product failed to Update
    productFatch: All Product Fetch Successfully
    productFatchErr: Failed to Fetch Product
    productSelect: Product Retrieved
    productSelectErr: Failed to Retrieved the Product
    productDelete: Product Deleted Successfully
